name: "CloudRDP [16:17:02] - RDP-INSTANCE-1"
on:
  workflow_dispatch:
jobs:
  rdp:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Setup RDP
        run: |
          export BACKEND_URL="https://tall-crews-make.loca.lt"
          export INSTANCE_ID="d919c5d6-07b4-48fc-a7ec-4dc595a450a6"
          bash scripts/RDP-INSTANCE-1_setup.sh

      - name: Report RDP Ready
        run: |
          for i in {1..3}; do
            HTTP_STATUS=$(curl -sSL -k -o /dev/null -w "%{http_code}" -X POST "https://tall-crews-make.loca.lt/instance/d919c5d6-07b4-48fc-a7ec-4dc595a450a6/ready" -H "Content-Type: application/json" -H "Bypass-Tunnel-Reminder: true" -d "{\"status\": \"ready\"}")
            if [ "$HTTP_STATUS" -eq 200 ]; then break; fi
            sleep 3
          done
      
      - name: Keep Alive
        run: sleep 21600
